<template>
  <div>
    <nuxt-picture
      src="/img/florian-skullmasher-ledru.jpg"
      class="hero-image"
    />
    <nuxt-picture
      src="/img/florian-skullmasher-ledru-square.jpg"
      class="hero-image-desktop"
    />
  </div>
</template>
